version: "3.8"

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongodb-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3

  mongodbui:
    image: mongo-express
    ports: 
      - 9090:8081
    networks:
      - mongodb-network  
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017

networks:
  mongodb-network:
    name: mongodb-network
    external: true

volumes:
  mongodb_data: